In [555]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [556]:
dallas = pd.read_csv("dallas.csv")
dallas.head(2)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Animal Id,Animal Type,Animal Breed,Kennel Number,Kennel Status,Tag Type,Activity Number,Activity Sequence,Source Id,Census Tract,Council District,Intake Type,Intake Subtype,Intake Total,Reason,Staff Id,Intake Date,Intake Time,Due Out,Intake Condition,Hold Request,Outcome Type,Outcome Subtype,Outcome Date,Outcome Time,Receipt Number,Impound Number,Service Request Number,Outcome Condition,Chip Status,Animal Origin,Additional Information,Month,Year
0,A0144701,DOG,HAVANESE,VT 12,IMPOUNDED,NaN,NaN,1,P0098773,006301,4,OWNER SURRENDER,GENERAL,1,PERSNLISSU,CDM,11/08/2019,15:48:00,11/14/2019,APP SICK,NaN,RETURNED TO OWNER,WALK IN,11/09/2019,11:31:00,R19-558731,K19-486742,NaN,APP SICK,SCAN CHIP,OVER THE COUNTER,RETURNED TO OWNER,NOV.2019,FY2020
1,A0442587,DOG,TERRIER MIX,FREEZER,IMPOUNDED,NaN,NaN,1,P0492284,007102,2,OWNER SURRENDER,DEAD ON ARRIVAL,1,OTHRINTAKS,CDM,11/10/2019,14:18:00,11/10/2019,DEAD,NaN,DEAD ON ARRIVAL,DISPOSAL,11/10/2019,00:00:00,NaN,K19-486954,NaN,DEAD,SCAN CHIP,OVER THE COUNTER,NaN,NOV.2019,FY2020

In [557]:
austin_intakes = pd.read_csv("austin_intakes.csv")
austin_intakes.head(2)

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver

In [558]:
austin_outcomes = pd.read_csv("austin_outcomes.csv")
austin_outcomes.head(2)

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/18/2018 04:02:00 PM,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown

In [559]:
# separate the date and time of intake
def separate_date(time):
    full = str(time)
    date = full[0:10]

    return date

def separate_time(time):
    full = str(time)
    time = full[11:]

    return time

In [560]:
austin_outcomes["Outcome Date"] = austin_outcomes["DateTime"].apply(separate_date)
austin_outcomes["Outcome Time"] = austin_outcomes["DateTime"].apply(separate_time)
austin_outcomes.drop(["DateTime","MonthYear"],axis=1, inplace=True)
austin_outcomes

,Animal ID,Name,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color,Outcome Date,Outcome Time
0,A794011,Chunk,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White,05/08/2019,06:20:00 PM
1,A776359,Gizmo,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown,07/18/2018,04:02:00 PM
2,A720371,Moose,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff,02/13/2016,05:59:00 PM
3,A674754,NaN,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby,03/18/2014,11:47:00 AM
4,A689724,*Donatello,08/01/2014,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Black,10/18/2014,06:52:00 PM
...,...,...,...,...,...,...,...,...,...,...,...,...
117848,A817873,Shae,08/01/2017,Return to Owner,NaN,Dog,Intact Female,2 years,German Shepherd,Brown/Black,05/30/2020,05:17:00 PM
117849,A817831,NaN,05/27/2018,Transfer,Partner,Dog,Intact Male,2 years,Cairn Terrier,Black/Brown,05/27/2020,02:32:00 PM
117850,A818021,NaN,03/30/2020,Euthanasia,Rabies Risk,Other,Unknown,2 months,Bat,Brown/Brown,05/31/2020,09:36:00 AM
117851,A818020,NaN,03/30/2020,Euthanasia,Rabies Risk,Other,Unknown,2 months,Bat,Brown/Brown,05/31/2020,09:35:00 AM
117852,A805538,Brooklyn,09/28/2017,Adoption,NaN,Dog,Spayed Female,2 years,Treeing Cur Mix,Tan,05/30/2020,01:00:00 PM

In [561]:
austin_intakes["Intake Date"] = austin_intakes["DateTime"].apply(separate_date)
austin_intakes["Intake Time"] = austin_intakes["DateTime"].apply(separate_time)
austin_intakes.drop(["DateTime","MonthYear"],axis=1, inplace=True)
austin_intakes

,Animal ID,Name,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Intake Date,Intake Time
0,A786884,*Brock,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor,01/03/2019,04:19:00 PM
1,A706918,Belle,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver,07/05/2015,12:59:00 PM
2,A724273,Runster,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White,04/14/2016,06:43:00 PM
3,A665644,NaN,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico,10/21/2013,07:59:00 AM
4,A682524,Rio,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,06/29/2014,10:38:00 AM
...,...,...,...,...,...,...,...,...,...,...,...,...
117520,A818022,NaN,8922 Menchaca Rd in Austin (TX),Stray,Injured,Cat,Intact Male,2 years,Domestic Shorthair,Black/Black,05/31/2020,01:32:00 AM
117521,A818029,Blue,8003 I35 Sv Rd in Austin (TX),Stray,Normal,Dog,Spayed Female,6 years,Labrador Retriever,Black,05/30/2020,07:30:00 AM
117522,A817784,*Libby,Derby Downs And Winter Haven in Austin (TX),Stray,Injured,Dog,Intact Female,2 years,Staffordshire,Black/White,05/26/2020,12:44:00 PM
117523,A818018,NaN,Research And Duval in Austin (TX),Stray,Injured,Dog,Neutered Male,4 years,Pit Bull/Chinese Sharpei,Brown/White,05/30/2020,03:36:00 PM
117524,A815288,Bella,13901 Suncrest in Travis (TX),Owner Surrender,Normal,Dog,Intact Female,1 year,Anatol Shepherd,Fawn,05/31/2020,12:25:00 PM

In [562]:
merged_austin = pd.merge(austin_intakes, austin_outcomes, left_on=["Animal ID","Color","Animal Type","Breed","Name"],
                        right_on=["Animal ID","Color","Animal Type","Breed","Name"])
merged_austin.drop(["Found Location"],axis=1, inplace=True)
merged_austin

,Animal ID,Name,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Intake Date,Intake Time,Date of Birth,Outcome Type,Outcome Subtype,Sex upon Outcome,Age upon Outcome,Outcome Date,Outcome Time
0,A786884,*Brock,Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor,01/03/2019,04:19:00 PM,01/03/2017,Transfer,Partner,Neutered Male,2 years,01/08/2019,03:11:00 PM
1,A706918,Belle,Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver,07/05/2015,12:59:00 PM,07/05/2007,Return to Owner,NaN,Spayed Female,8 years,07/05/2015,03:13:00 PM
2,A724273,Runster,Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White,04/14/2016,06:43:00 PM,04/17/2015,Return to Owner,NaN,Neutered Male,1 year,04/21/2016,05:17:00 PM
3,A665644,NaN,Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico,10/21/2013,07:59:00 AM,09/21/2013,Transfer,Partner,Intact Female,4 weeks,10/21/2013,11:39:00 AM
4,A682524,Rio,Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,06/29/2014,10:38:00 AM,06/29/2010,Return to Owner,NaN,Neutered Male,4 years,07/02/2014,02:16:00 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151905,A818015,NaN,Stray,Normal,Cat,Unknown,2 days,Domestic Shorthair,Orange Tabby,05/30/2020,02:58:00 PM,05/28/2020,Transfer,Partner,Unknown,2 days,05/30/2020,04:50:00 PM
151906,A818014,NaN,Stray,Normal,Cat,Unknown,2 days,Domestic Shorthair,Orange Tabby/White,05/30/2020,02:58:00 PM,05/28/2020,Transfer,Partner,Unknown,2 days,05/30/2020,04:50:00 PM
151907,A818001,Swis,Stray,Normal,Dog,Spayed Female,2 years,German Shepherd Mix,Brown/Black,05/30/2020,09:44:00 AM,05/30/2018,Return to Owner,NaN,Spayed Female,2 years,05/30/2020,05:04:00 PM
151908,A818020,NaN,Wildlife,Normal,Other,Unknown,1 month,Bat,Brown/Brown,05/30/2020,09:33:00 PM,03/30/2020,Euthanasia,Rabies Risk,Unknown,2 months,05/31/2020,09:35:00 AM
151909,A818021,NaN,Wildlife,Normal,Other,Unknown,1 month,Bat,Brown/Brown,05/30/2020,09:33:00 PM,03/30/2020,Euthanasia,Rabies Risk,Unknown,2 months,05/31/2020,09:36:00 AM

In [563]:
dallas.drop(["Kennel Number","Activity Number","Tag Type","Activity Sequence","Source Id","Census Tract",
        "Council District","Intake Total","Staff Id","Receipt Number","Impound Number",
             "Service Request Number","Month","Year","Due Out","Additional Information",
            "Reason"],axis=1, inplace=True)

In [564]:
dallas.rename(columns= {"Animal Breed" : "Breed", "Animal Id" : "Animal ID"}, inplace = True)

In [565]:
dallas.head(2)

,Animal ID,Animal Type,Breed,Kennel Status,Intake Type,Intake Subtype,Intake Date,Intake Time,Intake Condition,Hold Request,Outcome Type,Outcome Subtype,Outcome Date,Outcome Time,Outcome Condition,Chip Status,Animal Origin
0,A0144701,DOG,HAVANESE,IMPOUNDED,OWNER SURRENDER,GENERAL,11/08/2019,15:48:00,APP SICK,NaN,RETURNED TO OWNER,WALK IN,11/09/2019,11:31:00,APP SICK,SCAN CHIP,OVER THE COUNTER
1,A0442587,DOG,TERRIER MIX,IMPOUNDED,OWNER SURRENDER,DEAD ON ARRIVAL,11/10/2019,14:18:00,DEAD,NaN,DEAD ON ARRIVAL,DISPOSAL,11/10/2019,00:00:00,DEAD,SCAN CHIP,OVER THE COUNTER

In [566]:
dallas["Animal Type"] = dallas["Animal Type"].str.capitalize()
dallas["Breed"] = dallas["Breed"].str.capitalize()
dallas["Kennel Status"] = dallas["Kennel Status"].str.capitalize()
dallas["Intake Type"] = dallas["Intake Type"].str.capitalize()
dallas["Intake Subtype"] = dallas["Intake Subtype"].str.capitalize()
dallas["Intake Condition"] = dallas["Intake Condition"].str.capitalize()
dallas["Outcome Type"] = dallas["Outcome Type"].str.capitalize()
dallas["Outcome Subtype"] = dallas["Outcome Subtype"].str.capitalize()
dallas["Outcome Condition"] = dallas["Outcome Condition"].str.capitalize()
dallas["Chip Status"] = dallas["Chip Status"].str.capitalize()
dallas["Animal Origin"] = dallas["Animal Origin"].str.capitalize()
dallas["Hold Request"] = dallas["Hold Request"].str.capitalize()

In [567]:
dallas["Animal Type"].unique()

array(['Dog', 'Cat', 'Bird', 'Wildlife', 'Livestock'], dtype=object)

In [568]:
merged_austin["Animal Type"].unique()

array(['Dog', 'Cat', 'Other', 'Bird', 'Livestock'], dtype=object)

In [569]:
#making the outcomes standardixe
def change_outcome(outcome):
    if (outcome == "Return to Owner"):
        return "Returned to owner"
    elif (outcome == 'Euthanasia'):
        return "Euthanized"
def change_intake(outcome):
    if (outcome == "Dispos req"):
        return "Euthanasia Request"
def change_condition(outcome):
    if (outcome == "Healthy"):
        return "Normal"
    elif(outcome == "Deceased"):
        return "Dead"

In [570]:
merged_austin["Outcome Type"] = merged_austin["Outcome Type"].apply(change_outcome)
dallas["Intake Type"]  = dallas["Intake Type"].apply(change_intake)
dallas["Intake Condition"] = dallas["Intake Condition"].apply(change_condition)

In [571]:
dallas.head(2)

,Animal ID,Animal Type,Breed,Kennel Status,Intake Type,Intake Subtype,Intake Date,Intake Time,Intake Condition,Hold Request,Outcome Type,Outcome Subtype,Outcome Date,Outcome Time,Outcome Condition,Chip Status,Animal Origin
0,A0144701,Dog,Havanese,Impounded,None,General,11/08/2019,15:48:00,None,NaN,Returned to owner,Walk in,11/09/2019,11:31:00,App sick,Scan chip,Over the counter
1,A0442587,Dog,Terrier mix,Impounded,None,Dead on arrival,11/10/2019,14:18:00,None,NaN,Dead on arrival,Disposal,11/10/2019,00:00:00,Dead,Scan chip,Over the counter

In [572]:
def change_time(time):
    full = str(time)
    hour = int(time[0:2])
    rest = time[2:]
    day = ""
    if (hour > 12):
        hour = str(0) + str(hour - 12)
        day = " PM"
    else:
        day = " AM"
    return str(hour) + str(rest) + str(day)

In [573]:
dallas["Intake Time"] = dallas["Intake Time"].apply(change_time)
dallas["Outcome Time"] = dallas["Outcome Time"].apply(change_time)

In [574]:
merged_austin.head(2)

,Animal ID,Name,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color,Intake Date,Intake Time,Date of Birth,Outcome Type,Outcome Subtype,Sex upon Outcome,Age upon Outcome,Outcome Date,Outcome Time
0,A786884,*Brock,Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor,01/03/2019,04:19:00 PM,01/03/2017,None,Partner,Neutered Male,2 years,01/08/2019,03:11:00 PM
1,A706918,Belle,Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver,07/05/2015,12:59:00 PM,07/05/2007,Returned to owner,NaN,Spayed Female,8 years,07/05/2015,03:13:00 PM

In [575]:
common = ["Animal ID","Intake Type","Breed","Animal Type","Intake Date","Intake Time","Intake Condition","Outcome Type","Outcome Subtype",
                "Outcome Date","Outcome Time"]

In [576]:
merged = pd.merge(dallas, merged_austin, left_on = common, right_on = common, how = "outer")

In [577]:
merged

,Animal ID,Animal Type,Breed,Kennel Status,Intake Type,Intake Subtype,Intake Date,Intake Time,Intake Condition,Hold Request,Outcome Type,Outcome Subtype,Outcome Date,Outcome Time,Outcome Condition,Chip Status,Animal Origin,Name,Sex upon Intake,Age upon Intake,Color,Date of Birth,Sex upon Outcome,Age upon Outcome
0,A0144701,Dog,Havanese,Impounded,None,General,11/08/2019,03:48:00 PM,None,NaN,Returned to owner,Walk in,11/09/2019,11:31:00 AM,App sick,Scan chip,Over the counter,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0442587,Dog,Terrier mix,Impounded,None,Dead on arrival,11/10/2019,02:18:00 PM,None,NaN,Dead on arrival,Disposal,11/10/2019,0:00:00 AM,Dead,Scan chip,Over the counter,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A0458972,Dog,Catahoula,Unavailable,None,At large,10/03/2019,11:08:00 AM,None,NaN,Returned to owner,Field,10/03/2019,01:36:00 PM,Treatable rehabilitable non-contagious,Scan no chip,Sweep,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A0525642,Dog,Germ shepherd,Impounded,None,General,10/11/2019,9:55:00 AM,None,Emergency rescue,Transfer,Medical-contagious,10/15/2019,05:35:00 PM,Treatable rehabilitable non-contagious,Scan chip,Sweep,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A0565586,Dog,Silky terrier,Unavailable,None,At large,11/08/2019,11:55:00 AM,None,Rescu only,Returned to owner,Walk in,11/09/2019,12:57:00 AM,App wnl,Scan chip,Over the counter,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175969,A818015,Cat,Domestic Shorthair,NaN,Stray,NaN,05/30/2020,02:58:00 PM,Normal,NaN,None,Partner,05/30/2020,04:50:00 PM,NaN,NaN,NaN,NaN,Unknown,2 days,Orange Tabby,05/28/2020,Unknown,2 days
175970,A818014,Cat,Domestic Shorthair,NaN,Stray,NaN,05/30/2020,02:58:00 PM,Normal,NaN,None,Partner,05/30/2020,04:50:00 PM,NaN,NaN,NaN,NaN,Unknown,2 days,Orange Tabby/White,05/28/2020,Unknown,2 days
175971,A818001,Dog,German Shepherd Mix,NaN,Stray,NaN,05/30/2020,09:44:00 AM,Normal,NaN,Returned to owner,NaN,05/30/2020,05:04:00 PM,NaN,NaN,NaN,Swis,Spayed Female,2 years,Brown/Black,05/30/2018,Spayed Female,2 years
175972,A818020,Other,Bat,NaN,Wildlife,NaN,05/30/2020,09:33:00 PM,Normal,NaN,Euthanized,Rabies Risk,05/31/2020,09:35:00 AM,NaN,NaN,NaN,NaN,Unknown,1 month,Brown/Brown,03/30/2020,Unknown,2 months
175973,A818021,Other,Bat,NaN,Wildlife,NaN,05/30/2020,09:33:00 PM,Normal,NaN,Euthanized,Rabies Risk,05/31/2020,09:36:00 AM,NaN,NaN,NaN,NaN,Unknown,1 month,Brown/Brown,03/30/2020,Unknown,2 months

In [578]:
merged = merged[["Animal ID","Animal Type","Breed","Color","Kennel Status","Chip Status","Intake Date", "Date of Birth","Intake Time",
                 "Intake Type", "Intake Subtype","Intake Condition", "Animal Origin", "Sex upon Intake", "Age upon Intake",
                "Outcome Date","Outcome Time","Outcome Type","Outcome Subtype",
                 "Outcome Condition","Hold Request","Sex upon Outcome", "Age upon Outcome"]]

In [579]:
months = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
monthsleap = {1:31,2:29,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}

In [580]:
def return_days(intake, outcome): 
    if (type(intake) == str and type(outcome) == str): 
    
        intake_month = int(intake[:2])
        intake_day = int(intake[3:5])
        intake_year = int(intake[6:])
    
        outcome_month = int(outcome[:2])
        outcome_day = int(outcome[3:5])
        outcome_year = int(outcome[6:])
    
        if (outcome_year == intake_year):
            if (outcome_month == intake_month):
                return int(outcome_day - intake_day + 1) #same month
            else: 
                if (outcome_year % 4 == 0):
                    return int((monthsleap[intake_month] - intake_day + 1) + getAllDays(intake_month, int(outcome_month), monthsleap) + outcome_day)
                else:
                    return int((months[intake_month] - intake_day + 1) + getAllDays(intake_month, int(outcome_month), months) + outcome_day)
            
        else: #year isn't the same
            if (outcome_year - intake_year == 1):
                daysAfterIntake = return_days(intake, "12/31/" + str(intake_year))
                daysToOutcome = return_days("01/01/" + str(outcome_year),outcome) 
                return int(daysAfterIntake + daysToOutcome)
            else: 
                daysAfterIntake = return_days(intake, "12/31/" + str(intake_year))
                daysToOutcome = return_days("01/01/" + str(outcome_year),outcome) 
                middleYears = getYears(intake_year+1,outcome_year)
                return int(daysAfterIntake + daysToOutcome +  middleYears)

In [581]:
def getAllDays(in_m,out_m,cal):
    between = out_m - in_m
    days = 0
    for i in range(1, between):
        days += cal[in_m + i] 
    return days

In [582]:
def getYears(in_y,out_y):
    days = 0
    for i in range(in_y,out_y):
        if(i % 4 == 0):
            days += 366
        else:
            days +=365
    return days

In [583]:
merged["Days In"] = merged.apply(lambda x: return_days(x['Intake Date'], x['Outcome Date']), axis=1)

In [601]:
merged["Days In"].sort_values(ascending=False).head(20)

174273    2348.0
174272    2324.0
90512     2305.0
175478    2304.0
137234    2278.0
109938    2268.0
142712    2246.0
43907     2244.0
82023     2239.0
82022     2237.0
82021     2230.0
25955     2224.0
30645     2221.0
131907    2219.0
43912     2214.0
30609     2213.0
30618     2198.0
88089     2193.0
30202     2193.0
42486     2192.0
Name: Days In, dtype: float64

In [607]:
merged.set_index("Animal ID")

,Animal Type,Breed,Color,Kennel Status,Chip Status,Intake Date,Date of Birth,Intake Time,Intake Type,Intake Subtype,Intake Condition,Animal Origin,Sex upon Intake,Age upon Intake,Outcome Date,Outcome Time,Outcome Type,Outcome Subtype,Outcome Condition,Hold Request,Sex upon Outcome,Age upon Outcome,Days In
Animal ID,,,,,,,,,,,,,,,,,,,,,,,
A0144701,Dog,Havanese,NaN,Impounded,Scan chip,11/08/2019,NaN,03:48:00 PM,None,General,None,Over the counter,NaN,NaN,11/09/2019,11:31:00 AM,Returned to owner,Walk in,App sick,NaN,NaN,NaN,2.0
A0442587,Dog,Terrier mix,NaN,Impounded,Scan chip,11/10/2019,NaN,02:18:00 PM,None,Dead on arrival,None,Over the counter,NaN,NaN,11/10/2019,0:00:00 AM,Dead on arrival,Disposal,Dead,NaN,NaN,NaN,1.0
A0458972,Dog,Catahoula,NaN,Unavailable,Scan no chip,10/03/2019,NaN,11:08:00 AM,None,At large,None,Sweep,NaN,NaN,10/03/2019,01:36:00 PM,Returned to owner,Field,Treatable rehabilitable non-contagious,NaN,NaN,NaN,1.0
A0525642,Dog,Germ shepherd,NaN,Impounded,Scan chip,10/11/2019,NaN,9:55:00 AM,None,General,None,Sweep,NaN,NaN,10/15/2019,05:35:00 PM,Transfer,Medical-contagious,Treatable rehabilitable non-contagious,Emergency rescue,NaN,NaN,5.0
A0565586,Dog,Silky terrier,NaN,Unavailable,Scan chip,11/08/2019,NaN,11:55:00 AM,None,At large,None,Over the counter,NaN,NaN,11/09/2019,12:57:00 AM,Returned to owner,Walk in,App wnl,Rescu only,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A818015,Cat,Domestic Shorthair,Orange Tabby,NaN,NaN,05/30/2020,05/28/2020,02:58:00 PM,Stray,NaN,Normal,NaN,Unknown,2 days,05/30/2020,04:50:00 PM,None,Partner,NaN,NaN,Unknown,2 days,1.0
A818014,Cat,Domestic Shorthair,Orange Tabby/White,NaN,NaN,05/30/2020,05/28/2020,02:58:00 PM,Stray,NaN,Normal,NaN,Unknown,2 days,05/30/2020,04:50:00 PM,None,Partner,NaN,NaN,Unknown,2 days,1.0
A818001,Dog,German Shepherd Mix,Brown/Black,NaN,NaN,05/30/2020,05/30/2018,09:44:00 AM,Stray,NaN,Normal,NaN,Spayed Female,2 years,05/30/2020,05:04:00 PM,Returned to owner,NaN,NaN,NaN,Spayed Female,2 years,1.0
A818020,Other,Bat,Brown/Brown,NaN,NaN,05/30/2020,03/30/2020,09:33:00 PM,Wildlife,NaN,Normal,NaN,Unknown,1 month,05/31/2020,09:35:00 AM,Euthanized,Rabies Risk,NaN,NaN,Unknown,2 months,2.0
A818021,Other,Bat,Brown/Brown,NaN,NaN,05/30/2020,03/30/2020,09:33:00 PM,Wildlife,NaN,Normal,NaN,Unknown,1 month,05/31/2020,09:36:00 AM,Euthanized,Rabies Risk,NaN,NaN,Unknown,2 months,2.0

In [596]:
return_days("01/29/2014","01/01/2014")

-27